import type { McpResourceTemplate, McpTool } from './types';

export const TOOL_DEFINITIONS: McpTool[] = [
    { name: 'editor_list_sessions', description: 'List every live DIN Studio session currently connected to the local bridge.', inputSchema: { type: 'object', properties: {}, additionalProperties: false } },
    { name: 'editor_get_state', description: 'Read the latest full state snapshot for a live DIN Studio session.', inputSchema: { type: 'object', properties: { sessionId: { type: 'string' } }, additionalProperties: false } },
    { name: 'editor_list_graphs', description: 'List graphs available in a live DIN Studio session.', inputSchema: { type: 'object', properties: { sessionId: { type: 'string' } }, additionalProperties: false } },
    { name: 'editor_get_graph', description: 'Read one graph from a live DIN Studio session. Defaults to the active graph.', inputSchema: { type: 'object', properties: { sessionId: { type: 'string' }, graphId: { type: 'string' } }, additionalProperties: false } },
    { name: 'editor_preview_operations', description: 'Preview a batch of DIN Studio operations against a live session without mutating it.', inputSchema: { type: 'object', properties: { sessionId: { type: 'string' }, operations: { type: 'array', items: { type: 'object' } } }, required: ['operations'], additionalProperties: false } },
    { name: 'editor_apply_operations', description: 'Apply a batch of DIN Studio operations to a live session.', inputSchema: { type: 'object', properties: { sessionId: { type: 'string' }, operations: { type: 'array', items: { type: 'object' } } }, required: ['operations'], additionalProperties: false } },
    { name: 'editor_import_patch', description: 'Import a patch JSON document into the active or specified live DIN Studio graph.', inputSchema: { type: 'object', properties: { sessionId: { type: 'string' }, graphId: { type: 'string' }, path: { type: 'string' }, text: { type: 'string' } }, additionalProperties: false } },
    { name: 'editor_export_patch', description: 'Export a live graph to patch JSON or normalize an offline patch file.', inputSchema: { type: 'object', properties: { sessionId: { type: 'string' }, graphId: { type: 'string' }, path: { type: 'string' }, outputPath: { type: 'string' } }, additionalProperties: false } },
    { name: 'editor_validate_patch', description: 'Validate and normalize a patch JSON document from text or a local file path.', inputSchema: { type: 'object', properties: { path: { type: 'string' }, text: { type: 'string' } }, additionalProperties: false } },
    { name: 'editor_generate_code', description: 'Generate React code from a live graph or an offline patch JSON document.', inputSchema: { type: 'object', properties: { sessionId: { type: 'string' }, graphId: { type: 'string' }, path: { type: 'string' }, text: { type: 'string' }, includeProvider: { type: 'boolean' } }, additionalProperties: false } },
    { name: 'editor_list_assets', description: 'List audio assets stored inside a live DIN Studio session.', inputSchema: { type: 'object', properties: { sessionId: { type: 'string' } }, additionalProperties: false } },
    { name: 'editor_ingest_asset_file', description: 'Read a local audio file and ingest it into a live DIN Studio asset library.', inputSchema: { type: 'object', properties: { sessionId: { type: 'string' }, path: { type: 'string' }, fileName: { type: 'string' }, mimeType: { type: 'string' } }, required: ['path'], additionalProperties: false } },
    { name: 'editor_app_status', description: 'Return the health status, version, session count, and bridge configuration of the DIN Studio MCP server.', inputSchema: { type: 'object', properties: {}, additionalProperties: false } },
    { name: 'editor_focus_window', description: 'Bring the DIN Studio application window to the foreground.', inputSchema: { type: 'object', properties: { sessionId: { type: 'string' } }, additionalProperties: false } },
    { name: 'editor_open_project', description: 'Open a DIN Studio project from a local directory path.', inputSchema: { type: 'object', properties: { sessionId: { type: 'string' }, path: { type: 'string', description: 'Absolute path to the project directory.' } }, required: ['path'], additionalProperties: false } },
    { name: 'editor_export_file', description: 'Export a live graph to a local file. Supports patch JSON and React code generation formats.', inputSchema: { type: 'object', properties: { sessionId: { type: 'string' }, graphId: { type: 'string' }, outputPath: { type: 'string', description: 'Absolute path where the exported file should be saved.' }, format: { type: 'string', enum: ['patch.json', 'react'], description: 'Export format. Defaults to patch.json.' } }, required: ['outputPath'], additionalProperties: false } },
];

export const RESOURCE_TEMPLATES: McpResourceTemplate[] = [
    { uriTemplate: 'din-studio://session/{sessionId}/state', name: 'DIN Studio Session State', description: 'Read the latest live state snapshot for one DIN Studio session.', mimeType: 'application/json' },
    { uriTemplate: 'din-studio://session/{sessionId}/graphs', name: 'DIN Studio Graph List', description: 'Read the graph inventory for one DIN Studio session.', mimeType: 'application/json' },
    { uriTemplate: 'din-studio://session/{sessionId}/graphs/{graphId}', name: 'DIN Studio Graph', description: 'Read one graph from a DIN Studio session.', mimeType: 'application/json' },
    { uriTemplate: 'din-studio://offline/patch/{encodedPath}', name: 'DIN Studio Offline Patch', description: 'Read and normalize a local patch JSON file. Encode the filesystem path component.', mimeType: 'application/json' },
];
